# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.3

jobs:
  test:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: cp .env.default .env
      - attach_workspace:
          at: ~/repo
      - run: npx hardhat test

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
